version: 2

models:
  - name: stg_openweather_values
    description: "Transforms pollutant data to have one row per city per timestamp, with pollutants as columns."
    columns:
      - name: city
        description: "The city where the air quality was measured."
        tests:
          - not_null
      - name: timestamp
        description: "The timestamp of the air quality measurement."
        tests:
          - not_null
      - name: pm2_5
        description: "Particulate matter 2.5 levels."
      - name: pm10
        description: "Particulate matter 10 levels."
      - name: no2
        description: "Nitrogen dioxide levels."
      - name: so2
        description: "Sulfur dioxide levels."
      - name: o3
        description: "Ozone levels."
      - name: co
        description: "Carbon monoxide levels."
